# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

strategy:
  matrix:
    linux:
      image.name: 'ubuntu-latest'
    mac:
      image.name: 'macos-latest'
    windows:
      image.name: 'windows-latest'

pool:
  vmImage: $(image.name)

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '2.7'
    addToPath: false
  displayName: 'Use Python 2.7'
  name: python2

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    addToPath: false
  displayName: 'Use Python 3.6'
  name: python3

# linux
#   Python 2.7.16
#   /opt/hostedtoolcache/Python/2.7.16/x64/python
# macOS
#   Python 2.7.16
#   /Users/runner/hostedtoolcache/Python/2.7.16/x64/python
# Windows
#   Python 2.7.16
#   C:\hostedtoolcache\windows\Python\2.7.16\x64\python.exe
- script: |
    $(python2.pythonLocation)/python --version
    $(python2.pythonLocation)/python -c "import sys; print(sys.executable)"
  displayName: Show version and location of 'python2' binary

# linux
#   Python 3.6.9
#   /opt/hostedtoolcache/Python/3.6.9/x64/python
# macOS
#   Python 3.6.9
#   /Users/runner/hostedtoolcache/Python/3.6.9/x64/python
# Windows
#   Python 3.6.8
#   C:\hostedtoolcache\windows\Python\3.6.8\x64\python.exe
- script: |
    $(python3.pythonLocation)/python --version
    $(python3.pythonLocation)/python -c "import sys; print(sys.executable)"
  displayName: Show version and location of 'python3' binary

- script: |
    $(python3.pythonLocation)/python -m pip install setuptools
    $(python3.pythonLocation)/python -m pip install --upgrade pip
    $(python3.pythonLocation)/python -m pip install regex
    $(python3.pythonLocation)/python -m pip install primer3-py
  displayName: Install 'AddTag' dependencies

- script: |
    $(python2.pythonLocation)/python -m pip install setuptools
    $(python2.pythonLocation)/python -m pip install --upgrade pip
    $(python2.pythonLocation)/python -m pip install numpy==1.16.4
    $(python2.pythonLocation)/python -m pip install git+https://github.com/MicrosoftResearch/Azimuth.git
  displayName: Install 'Azimuth' dependencies

- script: |
    $(python3.pythonLocation)/python -m pip install pytest pytest-azurepipelines pytest-cov
    $(python3.pythonLocation)/python -m pytest --cov source --cov-report xml --cov-report html tests/
  displayName: PyTest

#- script: |
#    ls
#  displayName: 'List contents of default folder $(Build.SourcesDirectory)'

- script: |
    $(python3.pythonLocation)/python addtag --help
  displayName: Usage

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
  displayName: 'Publish code coverage results'