#!/usr/bin/env python3

"""AddTag Copyright (c) 2016 Thaddeus D. Seher & Aaron Hernday"""

# addtag

# Import standard packages
import sys

# Raise a useful error if utilizing an incompatible version of Python
if (sys.version_info < (3, 5, 1)):
    raise Exception("AddTag requires Python >= 3.5.1. You are running with " + ".".join(map(str, sys.version_info[:3])) + ".")

# Import source code
import source

# Execute program
if (__name__ == "__main__"):
    source.Main()
