#!/usr/bin/env python3

"""AddTag Copyright (c) 2016 Thaddeus D. Seher & Aaron Hernday

Program for identifying unique endogenous gRNA sites
and creating unique synthetic gRNA sites.
"""

# addtag

import sys

# Raise a useful error if utilizing an incompatible version of Python
if (sys.version_info < (3, 5, 1)):
    raise Exception("AddTag requires Python >= 3.5.1. You are running with " + ".".join(map(str, sys.version_info[:3])) + ".")

# Import source code
import source

if (__name__ == "__main__"):
    source.main()
