#!/usr/bin/env python3

"""AddTag Copyright (c) 2016 Thaddeus D. Seher & Aaron Hernday

Program for identifying unique endogenous gRNA sites
and creating unique synthetic gRNA sites.
"""

# addtag

# Import source code
import source

if (__name__ == "__main__"):
    source.main()
